baseurl: "/tailpages"
url: "https://nicolasanaia.github.io/tailpages/"

# site information used in page title, meta data etc.
title: "Nicolas Anaia Personal Website"
description: This is the website for Nicolas Anaia

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Nicolas Anaia
author-bio: Desenvolvedor de Software
author-image: profile.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: CV
  permalink: cv

# use false to turn off any social media links
github: https://github.com/nicolasanaia
linkedin: https://linkedin.com/in/nicolasanaia/
medium: https://medium.com/@nicolasanaia
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
