baseurl: ""
url: "https://nicolasanaia.com"

# site information used in page title, meta data etc.
title: "Nicolas Anaia"
description: Know a bit more about Nicolas Anaia

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Nicolas Anaia
author-bio: Desenvolvedor de Software, estudante de Ciência e Tecnologia na Universidade Federal do ABC e apreciador de animes e mangás
author-image: profile.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: Sobre
  permalink: about
- text: Projetos
  permalink: projects
- text: Skills
  permalink: skills
- text: Contato
  permalink: contact

# use false to turn off any social media links
github: https://github.com/nicolasanaia
linkedin: https://linkedin.com/in/nicolasanaia/
medium: https://medium.com/@nicolasanaia
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
